---
- name: Install packages
  apt:
    name: "{{ prometheus_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Configure prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus
